name: Build Windows EXE

on:
  push:
    branches: ["main", "master"]
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build with Maven
        run: |
          mvn clean package dependency:copy-dependencies
          copy target\editor-texto-1.0-SNAPSHOT.jar target\dependency\app.jar

      - name: Create EXE with jpackage
        run: |
          jpackage `
            --type app-image `
            --name JaChar `
            --input target/dependency `
            --main-jar app.jar `
            --main-class Main `
            --icon src/assets/favicon.ico `
            --dest dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: JaChar
          path: dist/JaChar
